# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Richard J. Urban"
description: > # this means to ignore newlines until "email:"
   <i class="fa fa-book" aria-hidden="true"></i> <i class="fa fa-folder-open" aria-hidden="true"></i> <i class="fa fa-university" aria-hidden="true"></i> <i class="fa fa-users" aria-hidden="true"></i><br />
   Libraries, Archives, Museums, and the Humanities

email: richardjurban@gmail.com
#blog logo
logo: "/assets/images/rju_logo.jpg"
# blog cover
cover: "/assets/images/head.jpg"
# cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Richard J. Urban'
author: 'Richard J. Urban'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://richardjurban.net" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@musebrarian'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/musebrarian
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/musebrarian
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
