title: Richard J. Urban
email: richardjurban@gmail.com
description: "Libraries, Archives, Museums, and the Humanities – Digitally"
baseurl: ""
url: "https://www.richardjurban.net"
github_username: musebrarian
remote_theme: pages-themes/slate@v0.2.0
show_downloads: true
plugins:
  - jekyll-feed
  - jekyll-remote-theme
   